// Shared sample bibliography data for Niutero design directions.
window.NIU = window.NIU || {};

window.NIU.collections = [
  { id: 'all', name: 'My Library', icon: 'library', count: 184, depth: 0 },
  { id: 'interp', name: 'Interpretability', icon: 'folder', count: 42, depth: 1 },
  { id: 'saes', name: 'Sparse Autoencoders', icon: 'folder', count: 18, depth: 2 },
  { id: 'unlearn', name: 'Unlearning', icon: 'folder', count: 11, depth: 2 },
  { id: 'safety', name: 'Safety & Alignment', icon: 'folder', count: 31, depth: 1 },
  { id: 'toread', name: 'To Read', icon: 'star', count: 7, depth: 1 },
];

window.NIU.tagGroups = [
  { ns: 'topics', label: 'Topics' },
  { ns: 'wf', label: 'Workflow' },
];

window.NIU.tags = [
  { name: 'topics:mech-interp', color: '#1F8A5B' },
  { name: 'topics:sae', color: '#2A6FDB' },
  { name: 'topics:unlearning', color: '#B6792B' },
  { name: 'topics:eval', color: '#8A5BD9' },
  { name: 'wf:my-work', color: '#C98A2B' },
  { name: 'wf:to-cite', color: '#C2536B' },
  { name: 'wf:reproduced', color: '#2F8E8A' },
];

window.NIU.items = [
  {
    id: 1, type: 'conference',
    title: 'SAEs Are Good for Steering — If You Select the Right Features',
    authors: ['Arad, Dana', 'Belinkov, Yonatan', 'Mueller, Aaron'],
    creator: 'Arad et al.', year: 2025, venue: 'ICLR',
    fullVenue: 'International Conference on Learning Representations',
    tags: ['topics:sae', 'topics:mech-interp'], status: 'reading', pdf: true, stars: 3,
    added: '2026-05-26', cite: 'aradSAEsGoodSteering2025',
    doi: '10.48550/arXiv.2505.20809',
    url: 'https://arxiv.org/abs/2505.20809',
    abstract: 'Sparse autoencoders decompose model activations into interpretable features, but using them to steer behavior has produced mixed results. We show that careful feature selection — rather than the SAE itself — is the dominant factor, and propose a selection criterion that recovers reliable steering across tasks.',
  },
  {
    id: 2, type: 'conference',
    title: 'Identifying Functionally Important Features with End-to-End Sparse Dictionary Learning',
    authors: ['Braun, Dan', 'Taylor, Jordan', 'Goldowsky-Dill, Nicholas', 'Sharkey, Lee'],
    creator: 'Braun et al.', year: 2024, venue: 'NeurIPS',
    fullVenue: 'The Thirty-eighth Annual Conference on Neural Information Processing Systems',
    tags: ['topics:sae', 'topics:mech-interp', 'wf:reproduced'], status: 'done', pdf: true, stars: 4,
    added: '2026-05-24', cite: 'braunIdentifyingFunctionallyImportant2024',
    doi: '10.48550/arXiv.2405.12241',
    url: 'https://openreview.net/forum?id=7txPaUpUnc',
    abstract: 'Standard sparse dictionary learning recovers features that reconstruct activations well but may not be the features the model actually uses. We introduce end-to-end sparse dictionary learning, optimizing for features that are functionally important to the network\u2019s computation, and find they are sparser and more interpretable.',
  },
  {
    id: 3, type: 'preprint',
    title: 'Applying Sparse Autoencoders to Unlearn Knowledge in Language Models',
    authors: ['Farrell, Eoin', 'Lau, Yeu-Tong', 'Conmy, Arthur'],
    creator: 'Farrell et al.', year: 2024, venue: 'arXiv',
    fullVenue: 'arXiv preprint',
    tags: ['topics:sae', 'topics:unlearning'], status: 'unread', pdf: false, stars: 2,
    added: '2026-05-22', cite: 'farrellApplyingSparseAutoencoders2024',
    doi: '10.48550/arXiv.2410.19278',
    url: 'https://arxiv.org/abs/2410.19278',
    abstract: 'We investigate whether sparse autoencoder features can be used to remove targeted knowledge from a language model. Clamping interpretable features reduces performance on a forget set, but we find unintended degradation on retained capabilities, raising questions about feature locality.',
  },
  {
    id: 4, type: 'conference',
    title: 'The Reasoning-Memorization Interplay in Language Models Is Mediated by a Single Direction',
    authors: ['Hong, Jie', 'Park, Soomin', 'Verma, Rahul'],
    creator: 'Hong et al.', year: 2025, venue: 'ACL',
    fullVenue: 'Annual Meeting of the Association for Computational Linguistics',
    tags: ['topics:mech-interp', 'topics:eval', 'wf:my-work'], status: 'reading', pdf: true, stars: 3,
    added: '2026-05-20', cite: 'hongReasoningMemorizationInterplay2025',
    doi: '10.48550/arXiv.2503.11656',
    url: 'https://arxiv.org/abs/2503.11656',
    abstract: 'We identify a single linear direction in activation space that mediates the trade-off between reasoning and verbatim memorization. Ablating it shifts the model toward generalization, while amplifying it increases recall of training data.',
  },
  {
    id: 5, type: 'conference',
    title: 'SAEs Can Improve Unlearning: Dynamic Sparse Autoencoder Guardrails for Precision Unlearning',
    authors: ['Muhamed, Aashiq', 'Diab, Mona', 'Smith, Noah A.'],
    creator: 'Muhamed et al.', year: 2025, venue: 'ICML',
    fullVenue: 'International Conference on Machine Learning',
    tags: ['topics:sae', 'topics:unlearning', 'wf:to-cite'], status: 'unread', pdf: true, stars: 4,
    added: '2026-05-18', cite: 'muhamedSAEsCanImprove2025',
    doi: '10.48550/arXiv.2504.08192',
    url: 'https://arxiv.org/abs/2504.08192',
    abstract: 'We present Dynamic SAE Guardrails, a method that uses sparse autoencoder features as steerable guardrails for precision unlearning. By dynamically gating feature activations we remove targeted knowledge with substantially less collateral damage than prior gradient-based approaches.',
  },
  {
    id: 6, type: 'preprint',
    title: 'Model Unlearning via Sparse Autoencoder Subspace-Guided Projections',
    authors: ['Wang, Lei', 'Okafor, Chidi', 'Ivanova, Mila'],
    creator: 'Wang et al.', year: 2025, venue: 'arXiv',
    fullVenue: 'arXiv preprint',
    tags: ['topics:sae', 'topics:unlearning', 'topics:eval'], status: 'unread', pdf: true, stars: 2,
    added: '2026-05-15', cite: 'wangModelUnlearningSparse2025',
    doi: '10.48550/arXiv.2505.01234',
    url: 'https://arxiv.org/abs/2505.01234',
    abstract: 'We project model weights away from a subspace identified by sparse autoencoder features associated with the forget target. The approach is training-free and preserves general capabilities better than fine-tuning baselines on the WMDP benchmark.',
  },
  {
    id: 7, type: 'journal',
    title: 'Toward Monosemanticity: Decomposing Language Models With Dictionary Learning',
    authors: ['Bricken, Trenton', 'Templeton, Adly', 'Batson, Joshua'],
    creator: 'Bricken et al.', year: 2023, venue: 'Transformer Circuits',
    fullVenue: 'Transformer Circuits Thread',
    tags: ['topics:sae', 'topics:mech-interp', 'wf:reproduced', 'wf:my-work'], status: 'done', pdf: true, stars: 5,
    added: '2026-05-12', cite: 'brickenTowardMonosemanticity2023',
    doi: '',
    url: 'https://transformer-circuits.pub/2023/monosemantic-features',
    abstract: 'Using a sparse autoencoder, we extract thousands of interpretable, largely monosemantic features from a one-layer transformer. These features are more interpretable than neurons and can be used to steer, predict, and explain model behavior.',
  },
  {
    id: 8, type: 'conference',
    title: 'Scaling and Evaluating Sparse Autoencoders',
    authors: ['Gao, Leo', 'la Tour, Tom Dupr\u00e9', 'Tillman, Henk'],
    creator: 'Gao et al.', year: 2025, venue: 'ICLR',
    fullVenue: 'International Conference on Learning Representations',
    tags: ['topics:sae', 'topics:eval'], status: 'reading', pdf: true, stars: 4,
    added: '2026-05-10', cite: 'gaoScalingEvaluatingSparse2025',
    doi: '10.48550/arXiv.2406.04093',
    url: 'https://arxiv.org/abs/2406.04093',
    abstract: 'We study how sparse autoencoders scale with compute and width, introduce a k-sparse training objective that controls the sparsity-reconstruction trade-off directly, and propose new metrics for feature quality that correlate with downstream interpretability.',
  },
];
